version: "3.8"

services:
  # 메시지 큐 관리: Zookeeper
  zookeeper:
    image: bitnami/zookeeper:3.9.2
    container_name: news_zookeeper
    hostname: zookeeper
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    volumes:
      - zookeeper-data:/bitnami/zookeeper
    restart: unless-stopped

  # 메시지 큐: Kafka
  kafka:
    image: bitnami/kafka:3.7.0
    container_name: news_kafka
    hostname: kafka
    ports:
      - "9092:9092"
      - "9093:9093"
    depends_on:
      - zookeeper
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=INTERNAL://:9092,EXTERNAL://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://kafka:9092,EXTERNAL://localhost:9093
      - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL
      - ALLOW_PLAINTEXT_LISTENER=yes
    volumes:
      - kafka-data:/bitnami/kafka
    restart: unless-stopped

  # 데이터베이스: PostgreSQL 
  postgres:
    image: postgres:14
    container_name: news_postgres
    hostname: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: newsuser
      POSTGRES_PASSWORD: newspass
      POSTGRES_DB: newsdb
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./data:/backup
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U newsuser -d newsdb"]
      interval: 30s
      timeout: 5s
      retries: 3

# 볼륨 정의 (추가된 볼륨들 포함)
volumes:
  postgres-data:
    driver: local
  zookeeper-data:
    driver: local
  kafka-data:
    driver: local
